name: lambda-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: Build Typescript and deploy to Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Install dependencies. Build Typescript. Zip dist folder
        run: npm install && npm run build && cp -r ./node_modules dist && cd dist && zip -qq -r ./dist.zip . && mv dist.zip ..
      - name: Send zip to AWS lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.FUNCTION_NAME }}
          zip_file: dist.zip